// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: service_greet.proto

package greet

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_service_greet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_greet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_service_greet_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloReturn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReturn) Reset() {
	*x = HelloReturn{}
	mi := &file_service_greet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReturn) ProtoMessage() {}

func (x *HelloReturn) ProtoReflect() protoreflect.Message {
	mi := &file_service_greet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReturn.ProtoReflect.Descriptor instead.
func (*HelloReturn) Descriptor() ([]byte, []int) {
	return file_service_greet_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReturn) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_service_greet_proto protoreflect.FileDescriptor

const file_service_greet_proto_rawDesc = "" +
	"\n" +
	"\x13service_greet.proto\x12\x05greet\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"+\n" +
	"\fHelloRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\"#\n" +
	"\vHelloReturn\x12\x14\n" +
	"\x05reply\x18\x02 \x01(\tR\x05reply2;\n" +
	"\x05Greet\x122\n" +
	"\x05Greet\x12\x13.greet.HelloRequest\x1a\x12.greet.HelloReturn\"\x00B\x1fZ\x1dxgen-uranus/examples/pb/greetb\x06proto3"

var (
	file_service_greet_proto_rawDescOnce sync.Once
	file_service_greet_proto_rawDescData []byte
)

func file_service_greet_proto_rawDescGZIP() []byte {
	file_service_greet_proto_rawDescOnce.Do(func() {
		file_service_greet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_greet_proto_rawDesc), len(file_service_greet_proto_rawDesc)))
	})
	return file_service_greet_proto_rawDescData
}

var file_service_greet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_greet_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: greet.HelloRequest
	(*HelloReturn)(nil),  // 1: greet.HelloReturn
}
var file_service_greet_proto_depIdxs = []int32{
	0, // 0: greet.Greet.Greet:input_type -> greet.HelloRequest
	1, // 1: greet.Greet.Greet:output_type -> greet.HelloReturn
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_greet_proto_init() }
func file_service_greet_proto_init() {
	if File_service_greet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_greet_proto_rawDesc), len(file_service_greet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_greet_proto_goTypes,
		DependencyIndexes: file_service_greet_proto_depIdxs,
		MessageInfos:      file_service_greet_proto_msgTypes,
	}.Build()
	File_service_greet_proto = out.File
	file_service_greet_proto_goTypes = nil
	file_service_greet_proto_depIdxs = nil
}
